# yamllint disable rule:truthy
# yamllint disable rule:indentation
# yamllint disable rule:line-length
name: build image

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: downcase REPO
      run: |
        echo "DOCKER_USERNAME=${github.repository_owner,,}" >> ${GITHUB_ENV}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${DOCKER_USERNAME}/alpine-playit-agent
          ghcr.io/${DOCKER_USERNAME}/alpine-playit-agent
        tags: |
          type=edge,branch=main
          type=schedule,pattern={{date 'YYYY[w]WW[d]]d'}}
          type=match,pattern=v(.*),group=1
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${DOCKER_USERNAME}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
